# Generated by Django 5.1.4 on 2025-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='pending', max_length=700),
        ),
    ]
