# Generated by Django 5.1.4 on 2025-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='Employee', max_length=10),
        ),
    ]
